ENTRY(__guest_header)

SECTIONS
{
	. = 0x70000000;
	.guest_header : { KEEP(*(.guest_header)) }
	.text : { *(.text .text.*) }
	.rodata : { *(.rodata .rodata.*) }
	. = ALIGN(0x10000);
	.data : { *(.data .data.*) }
	.got : { *(.got .got.* .got.plt) }
	.guest_init : {
		__guest_init_start = .;
		KEEP(*(.guest_init))
		KEEP(*(.init_array .init_array.*))
		__guest_init_end = .;
	}
	.bss : { *(.bss .bss.*) *(COMMON) }
	. = ALIGN(0x1000);
	__guest_image_end = .;
	/DISCARD/ : { *(.comment) *(.note.*) *(.guest_fini) *(.eh_frame) }
}
